python train_colornet_vimeo_noloss.py  \
--mode test \
--dataset demo   \
--scale 8 \
--display 100 \
--batch_size 1  \
--step_size 50000 \
--gamma 0.5 \
--loss CharbonnierLoss \
--optim Adam \
--lr 0.0001  \
--checkpoints_dir ./exp_X8/ \
--checkpoint_file ./pretrained/X8_30w.pth \
--frame_num 2 \
--with_GAN_loss 0 \
--img_save_path result/ \
--net_type colornet1 \
--pretrained 0 \
--gpu_id 0 \
--snapshot 5000
echo "Done" 
